### ISSUE TITLE
react-kit: Props typings for native elements wrappers

### ISSUE THREAD

**Issue by AlekseyChepurko** [devexperts/dx-platform#143]
there are a lot of components that just a wrapper around native elements like https://github.com/devex-web-frontend/dx-platform/blob/master/packages/react-kit/src/components/Button/Button.tsx. A lot of props are duplicated from native props of react elements. Is there any sense to duplicate it manualy instead of merging with JSX typings ?
for example with typings for Button component:
```typescript
export type TFullButtonProps = JSX.IntrinsicElements['input'] & { ...customProps }
```

**Comment by sutarmin** [comment]
> Is there any sense to duplicate it manually instead of merging with JSX typings?

As per internal discussion, the main idea was not to depend implicitly on native/react APIs, e.g. if react typings change, we want to track if it's a breaking and decide the next published version to be major, if so.

Another interesting example is that if we will use the rest operator internally, to extract "all other props to pass to the native component", then it could lead to very subtle bugs when some property could unintendedly slip through to the native component.
